# permissions for end users to view wordpresses.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: wordpress-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: wordpress
    app.kubernetes.io/part-of: wordpress
    app.kubernetes.io/managed-by: kustomize
  name: wordpress-viewer-role
rules:
- apiGroups:
  - cache.example.com
  resources:
  - wordpresses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cache.example.com
  resources:
  - wordpresses/status
  verbs:
  - get
